Updated sanity-check to retry connections if RPC timeouts occurs

diff --git a/bin/slurm-sanity-check b/bin/slurm-sanity-check
--- a/bin/slurm-sanity-check
+++ b/bin/slurm-sanity-check
@@ -6,8 +6,8 @@ use_reason_format=N
 
 report() {
     str="`date +'%d-%b-%Y %H:%M'` $@"
-    [ $use_reason_format == "N" -a "$verbose" == "Y" ] && echo `hostname -s` $str
-    [ $use_reason_format == "Y" -a "$verbose" == "Y" ] && echo $@
+    [ $use_reason_format == "N" -a "$verbose" == "Y" ] && echo "sanity-check:" `hostname -s` $str
+    [ $use_reason_format == "Y" -a "$verbose" == "Y" ] && echo "sanity-check:" $@
 }
 
 # Parse arguments
@@ -104,6 +104,12 @@ if echo $nodekind | egrep -q '^s[0-9][0-9]$' ; then
   fi
 fi
 
+ping -c 1 -w 10 10.200.2.67 > /dev/null
+if [ $? -ne 0 ] ; then
+    report "can't ping s02n67 on 10G/IB"
+    exit 1
+fi
+
 
 # Check /scratch and / for free space
 AVAILBLOCKS=(`df /scratch`)
@@ -124,15 +130,24 @@ if [ ! -d /faststorage/home ]; then
   exit 1
 fi
 
-# Check connectivity by sending ICMP pings to two hosts.
+# Check NFS states
+# rpcinfo may time out even if NFS is running, thus we retry 10 times
 CHKHOSTS="gfs1 gfs3 gfs4 gfs5"
 failed_nfs_hosts=0
 for fs in $CHKHOSTS ; do
-  /usr/sbin/rpcinfo -T udp $fs nfs 4 >/dev/null 2>&1 
-  if [ $? -ne 0 ] ; then
-      report "$fs not running nfs"
-      exit 1
-  fi
+  for i in {0..9}; do
+    /usr/sbin/rpcinfo -T udp $fs nfs 3 >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+      if [ $i -eq 9 ]; then
+        report "RPC NFSv3 failed for $fs"
+        exit 1
+      else
+        sleep 2
+      fi
+    else
+      break
+    fi
+  done
 done 
 
 for i in 1 2 3 4 5 6 7 8 ; do
